baseURL = "https://tlh.dev"
languageCode = "en-us"
title = "the little hope"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Tan-Linh Ha"
    profilePic = "/totoro.png"
    description = "personal corner of an ordinary developer"
    githubUsername = "hatanlinh13"
    copyright = "&copy; 2022 [Tan-Linh Ha](https://tlh.dev). Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal). Subscribe [via RSS](/index.xml)."
    accent = "#8197bf"
    showBorder = false
    backgroundColor = "#eeeeee"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "about"
    weight = 1

[[menu.main]]
    url = "/blogs/"
    name = "blogs"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "projects"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "tags"
    weight = 4

[[menu.main]]
    url = "/cv.pdf"
    name = "curriculum vitae"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://twitter.com/hatanlinh13/"
    name = "fab fa-twitter"
    weight = 1

[[menu.icon]]
    url = "https://facebook.com/hatanlinh13/"
    name = "fab fa-facebook"
    weight = 2

[[menu.icon]]
    url = "https://linkedin.com/in/hatanlinh13/"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://github.com/hatanlinh13/"
    name = "fab fa-github"
    weight = 4

[[menu.icon]]
    url = "mailto:linh@tlh.dev"
    name = "fas fa-envelope"
    weight = 5
